# Generated by Django 5.0.4 on 2024-04-03 18:24

import authentication.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authentication.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "Administrador"),
                    (1, "Paciente"),
                    (2, "Médico"),
                    (3, "Nutricionista"),
                    (4, "Psicólogo"),
                    (5, "Personal Trainer"),
                    (6, "Outros"),
                ],
                default=6,
            ),
        ),
    ]
